### ISSUE TITLE
兄弟，有没有试过用新出的wdk10 1709配合vs2017编译map driver

### ISSUE THREAD

**Issue by icewiski** [nakating/PUBG-maphack-map#10]
vs2015和wdk10，sdk10的环境配置的超级不顺利，各种报错
看到wdk10 1709能在vs2017使用了，结果下来后还是编译不出
报ApiValidation : error : ApiComparer had an XmlException. Make sure XML file has correct format.
没想到这会你还在更新

**Comment by nakating** [comment]
我也编译不了他的驱动...

**Comment by icewiski** [comment]
求个驱动- -
微博fo你了。。

**Comment by uuaing** [comment]
vs2015+wdk1413, 顺利编译

**Comment by icewiski** [comment]
兄弟能给个编译好的驱动不。。。

**Comment by uuaing** [comment]
这个不能共用，你懂的

icewiski <notifications@github.com>于2017年11月6日 周一上午1:03写道：

**Comment by 1478450488** [comment]
编译出来但是怎么映射到内核层啊 
我用了dsefix 和blackbone  但是都不可以  有没有大佬能给点提示
