### ISSUE TITLE
Curiously where some of the code you get from?

### ISSUE THREAD

**Issue by uuaing** [nakating/PUBG-maphack-map#11]
Hi, I just found the facing direction code includes the draw arrows are initially created by me, also includes other features. Never mind if you share the code here. But I'm just curiously where you get this. If it's possible please drop a mail to me at: uuaing@gmail.com.

**Comment by nakating** [comment]
啊..十分抱歉， 我是从`jerrytang67/helloworld` 这里找的代码， 我还奇怪那个    `//draw arrow -- uuaing` 是啥来着...  是我的错， 我去加上相关说明。

**Comment by uuaing** [comment]
😂不用没事，我就是好奇。那我知道原因了。。哈
你的手机版功能很不错，文字处理得也很美观，不错😁，顺便一个问题，触屏缩放感觉有些幅度太大，要哪里调小一点？

Naka <notifications@github.com>于2017年11月6日 周一上午1:16写道：

**Comment by nakating** [comment]
```
    // 缩放
    // 手势
    var lastScale = 0;
    hammertime.on('pinchmove', function (ev) {
        zoomByScale(lastScale + (lastScale - ev.scale));
        lastScale = ev.scale;
    });
```

这里的实现有点问题， 扩大后反向缩小是没有响应的，依然被当成了放大的scale...  有空是得改一下了

**Comment by uuaing** [comment]
Ok，另外，物品显示有好的方案吗，我现在的实现很杂很乱，名称都堆在一起了。

**Comment by nakating** [comment]
我打算加个筛选功能， 悬浮个按钮来筛选对应的物品类别。   不过这也是个缓解方案.. 叠在一起没有什么好的办法

**Comment by uuaing** [comment]
可以考虑加一个top bar，控制车辆显示与否，次要装备筛选，当前范围有什么重要装备之类，只是想到，我也还没有实现

Naka <notifications@github.com>于2017年11月6日 周一下午12:01写道：

**Comment by huangfengye** [comment]
这个有意思。。https://puu.sh/yf4N4/5a6bbd54ed.png

**Comment by nakating** [comment]
楼歪了.. 先关了
