### ISSUE TITLE
我看到您有中文注释就说中文了

### ISSUE THREAD

**Issue by fakersaber** [nakating/PUBG-maphack-map#15]
我参照写了一个C++的ESP，但是您的这种hack方式让我大开眼界，原理是不是通过接受服务器的数据包然后加工上去？如果是这样，怎么获取相应对象的地址呢，这样是不是也不能实现自瞄呢。希望您能解答，十分感谢

**Comment by violarulan** [comment]
原理还是借助 Kernel Driver 读内存，把读到的数据展示到这个 Web 界面

https://github.com/jussihi/PUBG-map-hack/blob/master/usermode%20app/hackControl/GameDataParser.hpp

**Comment by nakating** [comment]
Kernel Driver RPM读 Ajax到 node webserver,  webSocket到地图。

现在好像并没有成熟完整的package解析方案..
