### ISSUE TITLE
help me please

### ISSUE THREAD

**Issue by dideodn83** [nakating/PUBG-maphack-map#16]
Do I need to run both the kernel driver and usermode app?

I finished it all in order to make it.

But it does not work

**Comment by Allen399499** [comment]
you can add some code to print is the usermode app got the driver address

**Comment by younotme2** [comment]
HOW? when i type base my base always set to 0.. why? that's my kernel driver or usermode app wrong?

**Comment by wzx888** [comment]
Can you help me? I'm willing to pay for it
