### ISSUE TITLE
Hi may i get some help for the kernel driver

### ISSUE THREAD

**Issue by 1478450488** [nakating/PUBG-maphack-map#17]
i have already try to use the dsefix and BB to manual map the driver into kernel land,but the dsefix said is success but actually is not and the BB return the status 0xC0000022 and 0xC0000034 can you please tell me some tips of how to get this work ?
 Ton of thanks

**Comment by violarulan** [comment]
You use DSEFix to disable DSE and BB to load the driver? Did you got BSOD after a while?

**Comment by 1478450488** [comment]
yes i got a BSOD after nearly half hour and i use DSEFix -e to restore it but the driver still not work

**Comment by RealKallos** [comment]
Cause you can't break DSE's Integrity Check if you are on win10
don't waste your time to resolve that bsod problem  just use win7 
or find other way. also you can solve this problem to sign your drvier.

**Comment by 1478450488** [comment]
ok  thanks

**Comment by nakating** [comment]
this looks like resolve?
