### ISSUE TITLE
小白求帮助（谢谢大佬）

### ISSUE THREAD

**Issue by innovationb1ue** [nakating/PUBG-maphack-map#20]
下载了nodejs且安装后，找不到npm install，还有后面怎么run service. 研究了半天了还是不会用。。求一个更详细的使用说明T_T....

**Comment by jerrytang67** [comment]
安装 node 就有NPM了

**Comment by nakating** [comment]
看起来Kernel Driver那边也会卡顿很久... 相比较来说map这边已经开箱即食了。

node还是很简单的， 稍微找一些十分钟上手的文章看看吧。
