### ISSUE TITLE
can someone show a tutorial 

### ISSUE THREAD

**Issue by notrealgosu** [nakating/PUBG-maphack-map#22]
I mean should I edit anything also my vs2017 says your json.hpp file is not existing in the given directory ? I just downloaded the folder in here done nothing else someone forget to add json.hpp ? Also vs says there're some mistakes in code should i fix them by myself ? or am i doing something wrong ?

**Comment by nakating** [comment]
you know this map should working with https://github.com/jussihi/PUBG-map-hack , right?
