### ISSUE TITLE
How do I compile and what do I compile?

### ISSUE THREAD

**Issue by gggith5b** [nakating/PUBG-maphack-map#23]
Ive finished the nodejS part, my server is running, but do i need to compile the kernel and userapp folders or just the userapp one? If so, how do I do that, I'm searching for hours. Visual studio also can't help me.

Thanks in advance!

**Comment by nakating** [comment]
If you have any question of the kernel drive, please ask for jussihi/PUBG-map-hack,  I can't help you that.  I'm sorry.
