### ISSUE TITLE
I'm out of RPM way.

### ISSUE THREAD

**Issue by nakating** [nakating/PUBG-maphack-map#27]
I can't find a stable way to read process memory since the last update.
It looks like the blue hole won the war.

so the map is out of date now, but if you have a way to read memory, the map is still useful.

but I can't do kernel driver or something eles. so I'm out.

--------------------------------------------------------------

读不了内存了~没的玩了... 项目一时半会儿还不会停，不过也不会再投入更多精力了。

先这样吧，等找到了稳定的读取方式之后再说。

**Comment by Dragomitch** [comment]
The answer was provided on Jussihi repo, in Issues : https://github.com/jussihi/PUBG-map-hack/issues/105

As a pair programmer, could you help me to compile the programs ? I'm not a .Net/C++ dev, and I quiet struggle to make a build and to configure VC++2017 to compile everything.
Even more, I'm interested in all of that injection part (by drivers for eg ) that I would like to discover if possible with you :p !

Could you send me a way to communicate with you on my email -> orohimesama@gmail.com
Thanks :) !

**Comment by myloft** [comment]
https://github.com/jussihi/PUBG-map-hack/pull/107
https://github.com/myloft/PUBG-map-hack
可用

**Comment by BegYouNoXiu** [comment]
@myloft 
Changed, The problem now is that cannot find all actors

**Comment by myloft** [comment]
I fix it basing [Example code](https://www.unknowncheats.me/forum/1926233-post2753.html)
```c
for (int i = 0; i < ActorCount; i++)
	{
		encryptedActor encrActor;
		driver.Read(global::pid, ActorArray + (i * sizeof(encrActor)), &encrActor, sizeof(encrActor));
 
		DWORD decoded_xor = encrActor.xor ^ 0xCBAC;
		DWORD decoded_Index = encrActor.index ^ 0xD7AF5ABC;
 
		DWORD_PTR EncryptionTable = global::BaseAddress + 0x397B5A0;
 
		auto Xor1 = driver.RPM<DWORD>(EncryptionTable + sizeof(DWORD)*((byte)(decoded_Index)+0x300));
		auto Xor2 = driver.RPM<DWORD>(EncryptionTable + sizeof(DWORD)*((byte)((DWORD_PTR)decoded_Index >> 0x8) + 0x200));
		auto Xor3 = driver.RPM<DWORD>(EncryptionTable + sizeof(DWORD)*((byte)((DWORD_PTR)decoded_Index >> 0x10) + 0x100));
		auto Xor4 = driver.RPM<DWORD>(EncryptionTable + sizeof(DWORD)*((DWORD_PTR)(decoded_Index >> 0x18)));
		auto Real_Index = (Xor1^Xor2^Xor3^~Xor4) % 0x2B;
 
		DWORD_PTR pAActor = encrActor.ptr_table[Real_Index] ^ decoded_xor;
```
```c
struct encryptedActor
{
	uint64_t ptr_table[0x2B];
	uint16_t index;
	byte  unk2[0x6];
	uint16_t xor;
	byte  unk3[0x6];
};
```

**Comment by GianMrty** [comment]
Hi! Could you help me with the hack? I cant seem to use it. I only know java so i really need your help. If you could send me a tutorial on how to use it, it would be awesome.

**Comment by iZehnny** [comment]
I'm getting the error 'CANNOT GET /' i think it has something to do with routing, can anybody help me with  CURLWrapper.hpp?

**Comment by nakating** [comment]
我用MTA FairplayKD那个驱动鼓捣了好久， 还是失败了...读不出来， jussihi那个驱动也编译不出来，苦。

所以如果有人愿意一起折腾这个雷达，请联系我...

**Comment by nakating** [comment]
我搞定了，多谢各位
