### ISSUE TITLE
thank you 

### ISSUE THREAD

**Issue by xzfdsf21** [nakating/PUBG-maphack-map#29]
Thanks,it's worked well by your instruction.but i want to ask you a question how to display the toxic circle.

**Comment by nakating** [comment]
First, you should read the circle data from PUBG-map-hack, and send it to map.  paste the data struct here,  and then I'll show you how to draw it.

**Comment by xzfdsf21** [comment]
var ATslGameState = KReader.readUlong(m_PWorld + 0x00F8);



Vector3 blue = m_kReader->readVec(ATslGameState + 0x440, PROTO_NORMAL_READ);
float blueR = m_kReader->readType<float>(ATslGameState + 0x44C, PROTO_NORMAL_READ);

Vector3 white = m_kReader->readVec(ATslGameState + 0x450, PROTO_NORMAL_READ);
float whiteR = m_kReader->readType<float>(ATslGameState + 0x45C, PROTO_NORMAL_READ);

**Comment by xzfdsf21** [comment]
SafetyZonePosition = 0x045C;
        SafetyZoneRadius = SafetyZonePosition + 0xC;
        PoisonGasWarningPosition = 0x046C;
        PoisonGasWarningRadius = PoisonGasWarningPosition + 0xC;

**Comment by xzfdsf21** [comment]
Vector3 white = m_kReader->readVec(ATslGameState + 0x046C, PROTO_NORMAL_READ);
float whiteR = m_kReader->readType<float>(ATslGameState + 0x0478, PROTO_NORMAL_READ);

Vector3 blue = m_kReader->readVec(ATslGameState + 0x045C, PROTO_NORMAL_READ);
float blueR = m_kReader->readType<float>(ATslGameState + 0x0468, PROTO_NORMAL_READ);

w_data["zone"].emplace_back(json::object({ { "x", blue.X },{ "y", blue.Y },{ "r", blueR }}));  
w_data["zone"].emplace_back(json::object({ { "x", white.X },{ "y", white.Y },{ "r", whiteR } }));  

ATslGameState = m_kReader->readType<int64_t>(m_PWorld + 0x00F8, PROTO_NORMAL_READ);

int64_t ATslGameState;

**Comment by Zahariel1942** [comment]
OK, I'm working on it.  if you got some data struct, paste it here plz.

**Comment by xzfdsf21** [comment]
It's my pleasure.i have debugged the struct by firebase.it appears work well.

**Comment by xzfdsf21** [comment]
I have done it!
