### ISSUE TITLE
能否给一个联系方式

### ISSUE THREAD

**Issue by CoderMaurice** [nakating/PUBG-maphack-map#3]
能否给一点项目编译上的指导
没有用过VS
多谢!!!

**Comment by nakating** [comment]
不，npm开箱即食，请参阅Nodejs相关知识

**Comment by CoderMaurice** [comment]
需要把文件放到PUBG-map-hack里的某个文件夹吗?

**Comment by nakating** [comment]
稍后我会写一个Build instructions

**Comment by CoderMaurice** [comment]
多谢开源

**Comment by nakating** [comment]
readme has updated.

**Comment by CoderMaurice** [comment]
i see, but still have some question
1. what you mean` Working directory`? do i need to move  your project  to PUBG-map-hack ?
2. after run services node index.js, open  PUBG-map-hack ?

**Comment by nakating** [comment]
1 不需要
2 两个都可以独立运行，前后无所谓
