### ISSUE TITLE
Curlwrapper

### ISSUE THREAD

**Issue by iZehnny** [nakating/PUBG-maphack-map#30]
I'm getting the error 'CANNOT GET /' i think it has something to do with routing, can anybody help me with CURLWrapper.hpp? I'll paste mine under here. Thanks, cheers!

 sendData(std::string& w_data)
{
    try
    {
        struct curl_slist *headers = NULL;

        headers = curl_slist_append(headers, "Content-Type: application/json");

        curl_easy_setopt(m_curl, CURLOPT_VERBOSE, 0L);
        curl_easy_setopt(m_curl, CURLOPT_HTTPHEADER, headers);
        curl_easy_setopt(m_curl, http://127.0.0.1:7890/);
        curl_easy_setopt(m_curl, POST); 
        // curl_easy_setopt(curl, CURLOPT_TIMEOUT_MS, 30L);
        curl_easy_setopt(m_curl, CURLOPT_WRITEFUNCTION, write_data);
        curl_easy_setopt(m_curl, CURLOPT_POSTFIELDS, w_data.data());
        curl_easy_setopt(m_curl, CURLOPT_NOSIGNAL, 1);

        curl_easy_perform(m_curl);

        curl_slist_free_all(headers);
        curl_easy_reset(m_curl);
    }
    catch (std::exception& e)
    {
        std::cout << e.what() << std::endl;
        return -1;
    }
}

**Comment by xzfdsf21** [comment]
Something wrong with APP.

**Comment by nakating** [comment]
should be
    curl_easy_setopt(m_curl, CURLOPT_URL, "http://127.0.0.1:7890/");  // <---- here
    curl_easy_setopt(m_curl, CURLOPT_CUSTOMREQUEST, "POST");          // <---- here
