### ISSUE TITLE
i don't know what to do about this

### ISSUE THREAD

**Issue by freshz1** [nakating/PUBG-maphack-map#31]
it says me this error in node.js after I type "npm install" - "npm WARN PUBG-Livemap@1.0.0 No repository field."
anyone know what is this? xd, i feel a bit dumb about what i ask, but i'm really new about this

EDIT:
When i do "node index..js"
it hosts the map, but no one show up in that map, it is just like picture.

**Comment by nakating** [comment]
this map should working with https://github.com/jussihi/PUBG-map-hack,
just run both of them.

**Comment by freshz1** [comment]
i already did, but still nothing.

**Comment by nakating** [comment]
did you load the driver and read memory successfully?

**Comment by freshz1** [comment]
well with that i think i need help, because i'm new at this as i said and probably i don't even know what i'm doing what what should look right, if you can contact me on discord - freshz#8664

**Comment by nakating** [comment]
if you have problem with load&read memory, you should ask jussihi, he is the author, just follow this: https://github.com/jussihi/PUBG-map-hack/issues

**Comment by freshz1** [comment]
got sent back here :D he said that it is nodejs side problem

**Comment by nakating** [comment]
lol.

when it says :

    D:\somepath>node index.js
    server running at localhost:7890

means the map it's running up with no error, check this.

**Comment by freshz1** [comment]
yeah, the server is like running, but none of the players showing up on the map.

**Comment by nakating** [comment]
ok, and now try to debug your *usermode app* , found out did it send the data to the map. set some breakpoint in CURLWrapper.hpp, and run it up.

**Comment by freshz1** [comment]
it says that windows sdk version (...} was not found, but i already got it installed

**Comment by nakating** [comment]
so it's going into kernel driver part... shame, I can't compile the driver too.  that's why I told you to ask jussihi.

**Comment by freshz1** [comment]
but I have to debug right that whole _usermode_ app folder or what, like I'm in confusion right now haha

**Comment by nakating** [comment]
you need the driver, usermode app and the map.  both of them.  if any one of them got some error,  the whole system could't working. good luck
