### ISSUE TITLE
cannot get /

### ISSUE THREAD

**Issue by iZehnny** [nakating/PUBG-maphack-map#32]
I have no idea why this is popping up.
https://gyazo.com/612837bfa79d4b3bdad8775c96964586
https://gyazo.com/2467612e356dbed60a8389c4a829b605
https://gyazo.com/dec7c8dc3dddf69ee1fd0ee432d82279
https://gyazo.com/a6041d75d44ea5761a0a8379b6c2d212

**Comment by ImVurse** [comment]
i get same error aswell :(

**Comment by nakating** [comment]
I cant get this,   need more infos.

**Comment by ImVurse** [comment]
i do the tutorial perfect but it also says
Cannot GET /
For me im not that good at coding so i dont know what info to give to you

**Comment by ImVurse** [comment]
i go to localhost:7890 and i have index.js open in node it doesnt work

**Comment by ImVurse** [comment]
it gives Cannot GET /

**Comment by iZehnny** [comment]
@nakating I made a video of how i installed it, at the end i added CURLWrapper to. https://www.youtube.com/watch?v=6MXnLEdOSio&feature=youtu.be

**Comment by nakating** [comment]
if you `npm install express`  npm will install `express` ONLY.

you need `npm install` to install all the packages in `package.json`

**Comment by nakating** [comment]
@iZehnny try it, and go on

**Comment by nakating** [comment]
and `CURLWrapper.hpp` is https://github.com/jussihi/PUBG-map-hack 's file.   you need download and compile the kernel driver and usermode app.

**Comment by iZehnny** [comment]
I'm trying the method you told me right now, thanks for the support btw.

**Comment by nakating** [comment]
the core: kernel driver.
the reader: usermode app
the map: PUBG-maphack-map

you need build all of this.

**Comment by iZehnny** [comment]
hmm, i'm still getting the same error. ill make a video so i can show you how i installed it

**Comment by iZehnny** [comment]
@nakating here is the second video https://www.youtube.com/watch?v=ClW6KQb6nsQ&feature=youtu.be

**Comment by iZehnny** [comment]
oops. uploaded the wrong video.

**Comment by iZehnny** [comment]
@nakating here is the new video, using the new instalation guide. https://www.youtube.com/watch?v=GJo3El-Zr88&feature=youtu.be

**Comment by ImVurse** [comment]
is there a tutorial on how to compile usermode app and kernel driver?

**Comment by iZehnny** [comment]
@ImVurse watch my video

**Comment by ImVurse** [comment]
im pretty sure thats not how u compile something.

**Comment by nakating** [comment]
I think you need learn some coding or computer knowledge, I'm sorry dude, build and compile something is a hard work. It's can't be done if your doesn't know what are you doing.

just go find some "batteries included" cheats.

**Comment by GallyPokkun** [comment]
@nakating Can you make a tutorial with all details please ? thank you very much

**Comment by BegYouNoXiu** [comment]
cannot get may be the root directory not true, i have seen when i run the node /a/b/index.js , fixed by cd /a/b/  ,node index.js
