### ISSUE TITLE
Map Not Displaying Anything

### ISSUE THREAD

**Issue by aerrohd** [nakating/PUBG-maphack-map#34]
Hello! All I did was install the files, including Node.js, and followed the directions of 
Install Nodejs. To your Working directory and run npm install to install package.
Run services node index.js. The Map will running at localhost:7890.
After I do all this, I go to the localhost:7890 and it just shows the regular pubg match. I made sure I was in a game too. Even in the node.js command prompt it said connected users (1). Is there anything I'm missing? Help would be much appreciated.

**Comment by nakating** [comment]
you know this map should working with https://github.com/jussihi/PUBG-map-hack , right?
