### ISSUE TITLE
Dear friend.

### ISSUE THREAD

**Issue by ruhey79** [nakating/PUBG-maphack-map#4]
Can you tell me how to configure this part?

http://prntscr.com/h65dgf
http://prntscr.com/h65dt2

**Comment by nakating** [comment]
I dont know what is this.   you should use your browser (hrome,firefox) open "http://localhost:7890/"

**Comment by ruhey79** [comment]
this is "kernel driver" "mapdriver.sin" 
Is it possible without using it?

**Comment by ruhey79** [comment]
http://prntscr.com/h65no9
http://prntscr.com/h65ntv

There is no response..

**Comment by ruhey79** [comment]
I opened it with chrome

http://prntscr.com/h65osz

**Comment by nakating** [comment]
Yes, map can "RUN" without PUBG-map-hack,  but map need PUBG-map-hack to send game data.

**Comment by nakating** [comment]
and "/id?=PLAYERINDEX" means  if you want to track player 3 just open "http://localhost:7890/?id=3"

**Comment by ruhey79** [comment]
Answer Thank you so much
I have not been able to build "mapdriver.sin"
Running a build will launch an unknown program
Can you help me?

http://prntscr.com/h661d1

**Comment by nakating** [comment]
I dont know. for PUBG-map-hack issues or questions you should ask jussihi

**Comment by ruhey79** [comment]
Did you build "mapdriver.sin"?

**Comment by nakating** [comment]
nope,  I use my personal reader without driver.

**Comment by ruhey79** [comment]
Can you share your reader? ..

**Comment by nakating** [comment]
You know that if when your hack is been public release,  it's not undetected anymore.  I'm sorry I cant help you.
