### ISSUE TITLE
do you have new offsets for the usermodeapp, thank you! 

### ISSUE THREAD

**Issue by Allen399499** [nakating/PUBG-maphack-map#41]
@nakating

**Comment by 0x04c11db7** [comment]
I update it in my fork.
[](https://github.com/myloft/PUBG-map-hack)
Can you give me some help in using pubg-map-hack write memory

**Comment by 0x04c11db7** [comment]
@Allen399499

**Comment by Allen399499** [comment]
@myloft sure, plz let me know how can I contact you.

**Comment by 0x04c11db7** [comment]
@Allen399499 Maybe you can contact me by using telegram name @iloft

**Comment by Allen399499** [comment]
can't send message to you this moment, can you try @allen399499  via telegram?
