### ISSUE TITLE
大佬，求帮助啊。

### ISSUE THREAD

**Issue by ghost** [nakating/PUBG-maphack-map#43]
C:\Users\Administrator>sc start mapDriver

SERVICE_NAME: mapDriver
TYPE : 1 KERNEL_DRIVER
STATE : 4 RUNNING
(STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
WIN32_EXIT_CODE : 0 (0x0)
SERVICE_EXIT_CODE : 0 (0x0)
CHECKPOINT : 0x0
WAIT_HINT : 0x0
PID : 0
FLAGS :

usermode app：
base
Base set to: 0

这个是为什么啊，我驱动已经加载了还是0，求指点。

**Comment by ghost** [comment]
可以运行了

**Comment by dyy1993** [comment]
我也是这个问题 怎么弄的 大哥
