### ISSUE TITLE
终于成功显示了，大佬能改下地图自动旋转一直朝北吗，不太懂js之类的。

### ISSUE THREAD

**Issue by ghost** [nakating/PUBG-maphack-map#44]
谢谢大佬。

**Comment by ghost** [comment]
还有物品显示的字在哪改 谢谢！

**Comment by z3500376** [comment]
usermode type.hpp里即可

**Comment by ghost** [comment]
@z3500376  大佬懂不懂js 指导下、、、

**Comment by dyy1993** [comment]
我在运行窗口 输入 start 没出出来反馈 请帮帮我老哥 @xuboweiqqqq 
 @z3500376

**Comment by ghost** [comment]
你要先输入base 在输入start。

**Comment by ghost** [comment]
这次更新完 没用了 等更新offset吧。

**Comment by dyy1993** [comment]
输入的，还是没用，能加个qq聊聊吗 771750834 谢谢大佬

**Comment by ghost** [comment]
base不等于0就行， 如果显示0 你驱动没加载起来。

**Comment by dyy1993** [comment]
我的等于0   驱动inf里面要填写的不知道对不对

**Comment by ghost** [comment]
驱动编译出来后，尝试着加载驱动吧。

**Comment by dyy1993** [comment]
我试试，谢谢

**Comment by dyy1993** [comment]
大佬，驱动加载不了，没有签名，又什么解决方法吗? @xuboweiqqqq

**Comment by ghost** [comment]
这个得自己想办法。

**Comment by ghost** [comment]
@z3500376 type.hpp物品里改成中文 网页里显示乱码 哪里的问题，所有文件均为utf-8

**Comment by dyy1993** [comment]
@xuboweiqqqq  大哥，可以帮帮我吗？搞了好几天了没搞定，卡在驱动这一步了，寻求帮助
