### ISSUE TITLE
Error while add a new device! 

### ISSUE THREAD

**Issue by giaphongdau** [nakating/PUBG-maphack-map#45]
I tried to run mapDriver but it ask me to create a new device, Im using nakating source, and successfully host at my localhost:7890 but when I create a new device, they can't connect to my host, I'm even add port forwarding to 49152 and 65535 , but still can't connect, Im also try 192.168.0.25:7890 , 127.0.0.1:7890 but still, they can't connect. Any ideas?
![123123123](https://user-images.githubusercontent.com/20694082/34455555-0214300a-ed47-11e7-9f41-b262a6be1e8a.png)
![cvcxvxcvxcvxc](https://user-images.githubusercontent.com/20694082/34455556-0222c9c6-ed47-11e7-8dbc-b892c67ea1b6.png)

**Comment by BadBrojo** [comment]
I can't seem to build the mapDriver in VS2015 =/.
![testpag](https://user-images.githubusercontent.com/34952646/34457575-aa565ae6-ed69-11e7-8541-f11284467c2f.png)

**Comment by hellsink** [comment]
@giaphongdau i'm having same issues.. Can you help me?

**Comment by IternaAdolfo** [comment]
Dig into the source code guys

**Comment by giaphongdau** [comment]
@KhanhDo Well, can you help me? Người Việt Nam cả mà :3

**Comment by eren3434** [comment]
@giaphongdau you couldn't do that helps you connect
