### ISSUE TITLE
Map is showing, not live information. mapDriver problem?

### ISSUE THREAD

**Issue by BadBrojo** [nakating/PUBG-maphack-map#47]
This is as far as I was able to get. I am able to show 1 connected user. 

I don't believe I built the memory reader correctly, I opened mapDriver and built it, same for hackControl, then I started the node index.js, however the map is not updating with real-time location. See below. 
![testpag](https://user-images.githubusercontent.com/34952646/34456838-842a85ae-ed55-11e7-9b4f-e1d1d26cc006.png)

**Comment by Badoosk** [comment]
@badbrojo i only get white Screen can u help?
