### ISSUE TITLE
MSBuild Error MSB8020

### ISSUE THREAD

**Issue by BadBrojo** [nakating/PUBG-maphack-map#48]
The build tools for windowskernelmodedriver10.0 (Platform Toolset = 'windowskernelmodedriver10.0') cannot be found. To build using the windowskernelmodedriver10.0 build tools, please install windowskernelmodedriver10.0 build tools. Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".

**Comment by giaphongdau** [comment]
Can you help me on this? 
https://github.com/nakating/PUBG-maphack-map/issues/45
