### ISSUE TITLE
question.

### ISSUE THREAD

**Issue by ruhey79** [nakating/PUBG-maphack-map#5]
I will only ask one question.

Did you use blackbone "mapdriver.sys"?

**Comment by nakating** [comment]
no, I'm not using any driver

**Comment by ruhey79** [comment]
The foundation of your program is https://github.com/jussihi/PUBG-map-hack
But do not you use "kerneldriver", "USERMODEAPP"?

**Comment by nakating** [comment]
Yes,  I use a edited usermodeapp, that doesn't need kerneldriver.

**Comment by ruhey79** [comment]
I know what I'm worried about.
I do not disclose it to anyone.
If you do not mind, would you give me a chance to try it?
I know this is not easy to ask.
God bless you.

**Comment by nakating** [comment]
Sorry , no.

**Comment by ruhey79** [comment]
Yes I do. Thanks for the answer.
Good luck.
