### ISSUE TITLE
error curl.j lib!!

### ISSUE THREAD

**Issue by hellsink** [nakating/PUBG-maphack-map#52]
Error	C1083	Cannot open include file: 'curl/curl.h': No such file or directory

1 - ![error](https://user-images.githubusercontent.com/35161568/34788106-c980d12a-f620-11e7-839c-b38f5cef0eda.PNG)
 
2 - ![error2](https://user-images.githubusercontent.com/35161568/34788107-c99fd480-f620-11e7-8150-0d50ba83e53e.PNG)
 
3 - ![error3](https://user-images.githubusercontent.com/35161568/34788451-c1f8418a-f621-11e7-826d-9980c61eaea5.PNG)

Mr. @nakating can you help me? Thx!!

**Comment by notrealgosu** [comment]
add include directory, the file path of downloaded file or copy curl.h to one of your include directories
