### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by yswcdmm** [nakating/PUBG-maphack-map#58]
我编译好了程序 内存驱动和应用交换程序改好了基址。为什么运行地图不显示 标号0 不断的在左上角跑？

**Comment by whtiehack** [comment]
你什么系统?驱动是用什么编译的? 驱动是怎么加载的?

**Comment by yswcdmm** [comment]
系统是win10。 驱动用VS2015编译。 驱动用 DSEFix 加载

**Comment by whtiehack** [comment]
base 有值?  看来是你坐标偏移没更新?

**Comment by yswcdmm** [comment]
base有 14XXXXX

**Comment by yswcdmm** [comment]
加个QQ如何？

**Comment by whtiehack** [comment]
你一步一步下断点看看数据读没读对吧.看map还早.

**Comment by yswcdmm** [comment]
谢谢你 现在程序可以运行找人 不过有BUG  就是捡完东西后地图就往最上跑了。
