### ISSUE TITLE
i don't know how to use

### ISSUE THREAD

**Issue by ljuwon321** [nakating/PUBG-maphack-map#6]
i read README.md file. but i can't understand
i download https://github.com/jussihi/PUBG-map-hack
and download this repo too.
so, I copied the files I received here from the file on the 'README.md' file to the ' Online map ' folder.
and I used the command ' npm install ' command from the ' Online Map ' folder. using nodejs
but i found error -> [npm WARN PUBG-mapper@1.0.0 No repository field.]
how can i do?
plz write more detail in README.md

**Comment by huangfengye** [comment]
it;s a warning...no error.

**Comment by ljuwon321** [comment]
Then, is it okay to ignore it?
And is there anything wrong?
After entering the " node index.js.
web server is open. but does the page appear blank on the page, and there is nothing.
how can i do?

**Comment by nakating** [comment]
Just start up your PUBG-map-hack. make sure you configure it's `CURLWrapper.hpp`.

**Comment by ljuwon321** [comment]
i need build?

**Comment by nakating** [comment]
Obviously, yes.
